# Generated by Django 6.0.1 on 2026-01-27 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='odoo_version',
            field=models.CharField(default='18', help_text="Version d'Odoo pour ce plan (ex: 16, 17, 18)", max_length=10),
        ),
    ]
