# Generated by Django 6.0.1 on 2026-01-27 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OdooInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Instance identifier (e.g. client1)', max_length=100, unique=True)),
                ('container_name', models.CharField(blank=True, help_text='Docker container name (auto-generated if empty)', max_length=100, null=True, unique=True)),
                ('db_name', models.CharField(max_length=100)),
                ('db_password', models.CharField(blank=True, max_length=100)),
                ('admin_password', models.CharField(blank=True, max_length=100)),
                ('domain', models.CharField(max_length=255, unique=True)),
                ('port', models.IntegerField(help_text='Assigned internal port', unique=True)),
                ('odoo_version', models.CharField(default='18', help_text='Odoo version (e.g., 16, 17, 18)', max_length=20)),
                ('status', models.CharField(choices=[('CREATED', 'Created - Pending Deployment'), ('DEPLOYING', 'Deploying'), ('RUNNING', 'Running'), ('STOPPED', 'Stopped'), ('ERROR', 'Error')], default='CREATED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='accounts.client')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='billing.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('START', 'Start'), ('STOP', 'Stop'), ('RESTART', 'Restart'), ('DELETE', 'Delete'), ('UPDATE', 'Update'), ('BACKUP', 'Backup'), ('RESTORE', 'Restore')], max_length=20)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('IN_PROGRESS', 'In Progress')], default='IN_PROGRESS', max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployment_logs', to='instances.odooinstance')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
